name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore super-agent.csproj

    - name: Publish
      run: dotnet publish super-agent.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=false -o publish_output

    - name: Compress Release
      run: Compress-Archive -Path publish_output/* -DestinationPath SuperAgent-${{ github.ref_name }}-win-x64.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: SuperAgent-${{ github.ref_name }}-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
